spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schoolit
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
      show-sql: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          .ssl:
            trust:*
          auth: true
          startttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

